### ISSUE TITLE
Not working on catalina

### ISSUE THREAD

**Issue by ElegantSoft** [damieng/setledsmac#16]
I have cataline 10.15.2 and not working

**Comment by adriaanph** [comment]
it works for me on catalina. what happens though is that the OS quarantines the executable because it isn't signed by Apple, so you have to override that. follow these steps:

1) in spotlight search, type "allow apps"
2) top of the list should be  "Security & Privacy" - select that
3) in the lower panel you should see the "setleds" executable listed - click the "Allow" button

that should be it!

**Comment by damieng** [comment]
Thanks @adriaanph ! 

Sorry I can't provide any more information myself, I've pretty much stopped using my mac and it is still running Mojave I think.
