### ISSUE TITLE
How do I run this program?

### ISSUE THREAD

**Issue by michelkoga** [damieng/setledsmac#8]
Sorry for my lack of knowledge, but how do I run this program in my mac?

**Comment by damieng** [comment]
The steps are:

1. Download the .tar.gz from https://github.com/damieng/setledsmac/releases/latest
2. Double-click on the .tar.gz to unpack it
3. Open up a Terminal window on your Mac (Applications > Utilities > Terminal)
4. Type `~/Downloads/setleds +caps` for example to turn the caps LED on

If you get an error on line 4 about permissions then you'll have to run it with `sudo ~/Downloads/setleds +caps` and type in your password - this is because newer versions of macOS have made the API necessary to interact with the low-level devices administrator-only.
